<a href="https://colab.research.google.com/github/panditamey1/nlp_refresher/blob/main/nlp_refresher_3_sentence_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install sentence-transformers

In [4]:
from sentence_transformers import SentenceTransformer, util

In [ ]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [6]:
model.encode("I can play football")

array([ 8.13747873e-04, -4.78702635e-02, -5.46214804e-02, -7.40517452e-02,
        2.86002140e-02, -6.41794829e-03,  9.97117162e-02,  4.60907370e-02,
        2.51831040e-02,  3.15213874e-02, -5.88467754e-02, -6.18997775e-02,
       -1.97526696e-03,  6.63417429e-02,  9.36580822e-02, -5.09104058e-02,
        1.45546542e-02, -5.06773554e-02, -4.22212742e-02, -1.97691899e-02,
       -4.52939644e-02,  5.22390939e-02, -4.97351699e-02, -1.34686902e-02,
       -6.99354187e-02,  1.92658640e-02, -6.40594692e-04,  4.30654064e-02,
       -6.67386204e-02, -3.93666364e-02, -1.36275562e-02,  2.01228205e-02,
        1.54604530e-02, -4.40132106e-03, -5.11671863e-02,  2.76662782e-02,
        4.66759466e-02, -8.27105120e-02,  5.51602133e-02,  5.41449338e-02,
       -5.28622977e-02, -1.35651156e-01,  5.95020270e-03,  6.66948184e-02,
        2.13348288e-02,  8.90368447e-02,  1.99604798e-02,  1.23213306e-02,
        2.13813614e-02,  3.54127325e-02,  5.98916113e-02,  7.10870624e-02,
       -8.76213424e-03,  

In [7]:
embeddings = model.encode(["I love football", "I can play football", "I like liverpool football club", "I am a fan of soccer"])

In [9]:
cos_sim = util.cos_sim(embeddings,embeddings)

In [10]:
cos_sim.shape

torch.Size([4, 4])

In [16]:
all_sentence_comb = []
for i in range(len(cos_sim) - 1 ):
  for j in range(i+1, len(cos_sim)):
    all_sentence_comb.append((cos_sim[i][j], i, j))

In [17]:
all_sentence_comb

[(tensor(0.6743), 0, 1),
 (tensor(0.5843), 0, 2),
 (tensor(0.6502), 0, 3),
 (tensor(0.3547), 1, 2),
 (tensor(0.4718), 1, 3),
 (tensor(0.5945), 2, 3)]

In [18]:
sorted_list = sorted(all_sentence_comb, key=lambda x:x[0], reverse = True)

In [19]:
sorted_list[:5]

[(tensor(0.6743), 0, 1),
 (tensor(0.6502), 0, 3),
 (tensor(0.5945), 2, 3),
 (tensor(0.5843), 0, 2),
 (tensor(0.4718), 1, 3)]

In [21]:
sentences = ["I love football", "I can play football", "I like liverpool football club", "I am a fan of soccer"]

In [23]:
for cos_sim, i, j in sorted_list:
  print("{}  {} {}".format(sentences[i],sentences[j], cos_sim))

I love football  I can play football 0.6743314266204834
I love football  I am a fan of soccer 0.6502246260643005
I like liverpool football club  I am a fan of soccer 0.594515323638916
I love football  I like liverpool football club 0.584286093711853
I can play football  I am a fan of soccer 0.471792072057724
I can play football  I like liverpool football club 0.3546545207500458


### semantic search

In [26]:
model2 = SentenceTransformer("clips/mfaq")

Downloading:   0%|          | 0.00/1.65k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.74k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/778 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/117 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/294 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/464 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py:370: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  "Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 "


In [29]:
from transformers import pipeline

qa_model = pipeline("question-answering")
question = "Where is my son?"
context = "My name is Merve and I live in İstanbul. But my wife lives in America and my son lives in London"
qa_model(question = question, context = context)


No model was supplied, defaulted to distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


{'score': 0.9775927066802979, 'start': 90, 'end': 96, 'answer': 'London'}

### clustering

In [30]:
from sklearn.cluster import KMeans
import numpy as np

embedder = SentenceTransformer('all-MiniLM-L6-v2')

# Corpus with example sentences
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'Horse is eating grass.',
          'A man is eating pasta.',
          'A Woman is eating Biryani.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.',
          'The cheetah is chasing a man who is riding the horse.',
          'man and women with their baby are watching cheetah in zoo'
          ]
corpus_embeddings = embedder.encode(corpus)

# Normalize the embeddings to unit length
corpus_embeddings = corpus_embeddings /  np.linalg.norm(corpus_embeddings, axis=1, keepdims=True)

In [31]:
corpus_embeddings.shape

(15, 384)

In [35]:
model =  KMeans(n_clusters=3)

In [36]:
model.fit(corpus_embeddings)

KMeans(n_clusters=3)

In [37]:
model.cluster_centers_

array([[-0.02720954, -0.01456458, -0.05828847, ..., -0.01079978,
         0.09163231, -0.00550729],
       [ 0.02371987, -0.00630608, -0.01295164, ...,  0.03634214,
        -0.01519625, -0.02679966],
       [ 0.01089153,  0.02386292,  0.0277095 , ...,  0.02359034,
         0.04765008,  0.01599437]], dtype=float32)

In [38]:
model.labels_

array([1, 1, 2, 1, 1, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0], dtype=int32)

In [42]:
labels = model.labels_
cluster_sent = {}
for index, label in enumerate(labels):
  #print("{}              belongs to cluster number : {}".format(corpus[index],label))
  if label not in cluster_sent:
    cluster_sent[label] = []
  cluster_sent[label].append(corpus[index])


In [43]:
cluster_sent

{1: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 2: ['Horse is eating grass.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.',
  'A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.',
  'A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.'],
 0: ['The girl is carrying a baby.',
  'The baby is carried by the woman',
  'man and women with their baby are watching cheetah in zoo']}